---
services:
  # Container management
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    environment:
      - TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data

  # Adblocking
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TS: TZ
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - './etc-pihole:/etc/pihole'

  # Smart home
  scrypted:
    container_name: scrypted
    image: "koush/scrypted"
    restart: unless-stopped
    ports:
      - "10443:10443"
    environment:
      - TZ
      - SCRYPTED_DOCKER_AVAHI=true
    volumes:
      - /etc/scrypted:/server/volume
    network_mode: host

  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
  
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /etc-homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ
    restart: unless-stopped
    privileged: true
    network_mode: host

  # Media
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    environment:
      - PUID
      - PGID
      - TZ
      - ADVERTISE_IP
      - PLEX_CLAIM
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./plexmediaserver:/config
      - /mnt/media:/mnt/media
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    network_mode: host

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - /etc-sonarr/data:/config
      - /mnt/media:/mnt/media
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - /etc-sonarr/data:/config
      - /mnt/media:/mnt/media
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - /etc-sabnzbd/config:/config
      - /mnt/media:/mnt/media
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ
    volumes:
      - /etc-overseerr/config:/app/config
    restart: unless-stopped

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - /etc-tautulli/config:/config
    restart: unless-stopped

  # Networking
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID
      - PGID
      - TZ
      - CLOUDFLARE_API_TOKEN
    volumes:
      - ./ddclient.conf:/config/ddclient.conf
    restart: unless-stopped

networks:
  default:
    external: true
    name: bahay
