services:
  # Container management
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    environment:
      - TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Service
  ntp:
    image: cturra/ntp:latest
    container_name: ntp_server
    restart: always
    environment:
      - NTP_SERVERS=au.pool.ntp.org
    ports:
      - "123:123/udp"
    network_mode: host

  # Adblocking
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TS: TZ
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_webserver_api_password: '${FTLCONF_webserver_api_password}'
    volumes:
      - './etc-pihole:/etc/pihole'
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  # Smart home
  scrypted:
    container_name: scrypted
    image: "koush/scrypted"
    restart: unless-stopped
    ports:
      - "10443:10443"
    environment:
      - TZ
      - SCRYPTED_DOCKER_AVAHI=true
    volumes:
      - /etc/scrypted:/server/volume
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./etc-homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  matter-server:
    image: ghcr.io/matter-js/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    # Required for mDNS to work correctly
    network_mode: host
    security_opt:
      # Needed for Bluetooth via dbus
      - apparmor:unconfined
    volumes:
      # Create an .env file that sets the USERDIR environment variable.
      - ${USERDIR:-$HOME}/docker/matter-server/data:/data/
      # Required for Bluetooth via D-Bus
      - /run/dbus:/run/dbus:ro
    # If you adjust command line, make sure to pass the default CMD arguments too:
    #command: --storage-path /data --paa-root-cert-dir /data/credentials --bluetooth-adapter 0


  # Media
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    environment:
      - PUID
      - PGID
      - TZ
      - ADVERTISE_IP
      - PLEX_CLAIM
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./plexmediaserver:/config
      - /mnt/plex:/mnt/plex
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - /etc-sonarr/data:/config
      - /mnt/media:/mnt/media
      - /mnt/plex:/mnt/plex
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - /etc-sonarr/data:/config
      - /mnt/media:/mnt/media
      - /mnt/plex:/mnt/plex
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - /etc-sabnzbd/config:/config
      - /mnt/media:/mnt/media
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ./etc-bazarr/config:/config
      - /mnt/media:/mnt/media
      - /mnt/plex:/mnt/plex
    ports:
      - 6767:6767
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ
    volumes:
      - /etc-overseerr/config:/app/config
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - /etc-tautulli/config:/config
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Websites
  jademontagu:
    image: ghcr.io/jmontagu/jademontagu.com:main
    container_name: jademontagu
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.opencontainers.image.source=https://github.com/JMontagu/jademontagu.com"

  # Networking
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID
      - PGID
      - TZ
      - CLOUDFLARE_API_TOKEN
    volumes:
      - ./ddclient.conf:/config/ddclient.conf
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  # MQTT
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./etc-mosquitto:/mosquitto
      - ./etc-mosquitto/data:/mosquitto/data
      - ./etc-mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883

  # Zigbee
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      - TZ
    volumes:
      - ./etc-mosquitto/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_9247da1379f5ef11a7bb96a29ed47d52-if00-port0:/dev/ttyUSB1


networks:
  default:
    external: true
    name: bahay
