services:
  # Container management
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    environment:
      - TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Adblocking
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TS: TZ
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_webserver_api_password: '${FTLCONF_webserver_api_password}'
    volumes:
      - './etc-pihole:/etc/pihole'
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  # Smart home
  scrypted:
    container_name: scrypted
    image: "koush/scrypted"
    restart: unless-stopped
    ports:
      - "10443:10443"
    environment:
      - TZ
      - SCRYPTED_DOCKER_AVAHI=true
    volumes:
      - /etc/scrypted:/server/volume
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./etc-homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  # Media
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    environment:
      - PUID
      - PGID
      - TZ
      - ADVERTISE_IP
      - PLEX_CLAIM
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./plexmediaserver:/config
      - /mnt/plex:/mnt/plex
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - /etc-sonarr/data:/config
      - /mnt/media:/mnt/media
      - /mnt/plex:/mnt/plex
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - /etc-sonarr/data:/config
      - /mnt/media:/mnt/media
      - /mnt/plex:/mnt/plex
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - /etc-sabnzbd/config:/config
      - /mnt/media:/mnt/media
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ./etc-bazarr/config:/config
      - /mnt/media:/mnt/media
      - /mnt/plex:/mnt/plex
    ports:
      - 6767:6767
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ
    volumes:
      - /etc-overseerr/config:/app/config
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - /etc-tautulli/config:/config
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Websites
  jademontagu:
    image: ghcr.io/jmontagu/jademontagu.com:main
    container_name: jademontagu
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.opencontainers.image.source=https://github.com/JMontagu/jademontagu.com"

  # Networking
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID
      - PGID
      - TZ
      - CLOUDFLARE_API_TOKEN
    volumes:
      - ./ddclient.conf:/config/ddclient.conf
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  default:
    external: true
    name: bahay
