---
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - 9000:9000/tcp
    environment:
      - TZ=Australia/Melbourne
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data

  scrypted:
    container_name: scrypted
    image: koush/scrypted
    restart: unless-stopped
    ports:
      - "10443:10443"
    environment:
      - TZ=Australia/Melbourne
      - SCRYPTED_DOCKER_AVAHI=true
    volumes:
      - /opt/scrypted:/server/volume
    network_mode: host

  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
    environment:
      TS: "Australia/Melbourne"
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './etc-pihole:/etc/pihole'
    restart: unless-stopped
